version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            sleep 180
            echo 'This is the delivery pipeline: hoge'
            exit 1
  test:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  before-merging:
    jobs:
      - build:
          name: build
          filters:
            branches: 
              only: /gh-readonly-queue\/main\/.*/
      - approval:
          type: approval
          filters:
            branches: 
              only: /gh-readonly-queue\/main\/.*/
          requires:
            - build
      - test:
          name: test-hoge
          filters:
            branches: 
              only: /gh-readonly-queue\/main\/.*/
          requires: 
            - approval
